on:
  pull_request:
    branches:
      - dev
    types: [closed]

jobs:
  jenkins:
    if: github.event.pull_request.merged == true
    name: Jenkins-action
    runs-on: ubuntu-latest
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: ${{ secrets.DEV_URL }}
          user: ${{ secrets.DEV_USER }}
          token: ${{ secrets.DEV_TOKEN }}
          job: ${{secrets.DEV_PROJECT}}